#!/usr/bin/env python3
import json

cities_data = [
    {"province_code": "01", "name_ar": "أدرار", "name_en": "Adrar"},
    {"province_code": "01", "name_ar": "عين صفرة", "name_en": "Ain Safra"},
    {"province_code": "01", "name_ar": "تيميمون", "name_en": "Timimoun"},
    {"province_code": "01", "name_ar": "رقان", "name_en": "Reggane"},
    {"province_code": "02", "name_ar": "الشلف", "name_en": "Chlef"},
    {"province_code": "02", "name_ar": "الحجاج", "name_en": "El Hadjadje"},
    {"province_code": "02", "name_ar": "أولاد بن عبد القادر", "name_en": "Ouled Ben Abdelkader"},
    {"province_code": "02", "name_ar": "عين مران", "name_en": "Ain Merane"},
    {"province_code": "03", "name_ar": "الأغواط", "name_en": "Laghouat"},
    {"province_code": "03", "name_ar": "تاجنة", "name_en": "Tadjnant"},
    {"province_code": "03", "name_ar": "حد الصحراء", "name_en": "Had Essahara"},
    {"province_code": "04", "name_ar": "أم البواقي", "name_en": "Oum El Bouaghi"},
    {"province_code": "04", "name_ar": "عين البيضاء", "name_en": "Ain Beida"},
    {"province_code": "04", "name_ar": "عين كرشة", "name_en": "Ain Kercha"},
    {"province_code": "05", "name_ar": "باتنة", "name_en": "Batna"},
    {"province_code": "05", "name_ar": "آريس", "name_en": "Aris"},
    {"province_code": "05", "name_ar": "تيغانمين", "name_en": "Tiganmine"},
    {"province_code": "06", "name_ar": "بجاية", "name_en": "Bejaia"},
    {"province_code": "06", "name_ar": "عمالو", "name_en": "Amalu"},
    {"province_code": "06", "name_ar": "أكبو", "name_en": "Akbou"},
    {"province_code": "07", "name_ar": "بسكرة", "name_en": "Biskra"},
    {"province_code": "07", "name_ar": "محمد بوديار", "name_en": "M'Chouneche"},
    {"province_code": "07", "name_ar": "جمورة", "name_en": "Jamora"},
    {"province_code": "08", "name_ar": "بئر الحاج", "name_en": "Bechar"},
    {"province_code": "08", "name_ar": "أولاد ميمون", "name_en": "Ouled Mimoun"},
    {"province_code": "08", "name_ar": "بني عزيز", "name_en": "Beni Aziz"},
    {"province_code": "09", "name_ar": "بليدة", "name_en": "Blida"},
    {"province_code": "09", "name_ar": "شرقة", "name_en": "Cheraga"},
    {"province_code": "09", "name_ar": "الزقاق", "name_en": "Azzeq"},
    {"province_code": "10", "name_ar": "البويرة", "name_en": "Bouira"},
    {"province_code": "10", "name_ar": "عين بسام", "name_en": "Ain Besam"},
    {"province_code": "10", "name_ar": "المقراني", "name_en": "El Mokrani"},
    {"province_code": "11", "name_ar": "تمنراست", "name_en": "Tamanrasset"},
    {"province_code": "11", "name_ar": "إيليزي", "name_en": "Illizi"},
    {"province_code": "11", "name_ar": "عين قزام", "name_en": "In Gall"},
    {"province_code": "12", "name_ar": "تبسة", "name_en": "Tebessa"},
    {"province_code": "12", "name_ar": "بئر العاتر", "name_en": "Bir El Ater"},
    {"province_code": "12", "name_ar": "أم علي", "name_en": "Oum Ali"},
    {"province_code": "13", "name_ar": "تلمسان", "name_en": "Tlemcen"},
    {"province_code": "13", "name_ar": "منصورة", "name_en": "Mansoura"},
    {"province_code": "13", "name_ar": "سبدو", "name_en": "Sebdou"},
    {"province_code": "14", "name_ar": "تيارت", "name_en": "Tiaret"},
    {"province_code": "14", "name_ar": "سيدي بخاري", "name_en": "Sidi Bakhti"},
    {"province_code": "14", "name_ar": "فرندة", "name_en": "Frenda"},
    {"province_code": "15", "name_ar": "تيزي وزو", "name_en": "Tizi Ouzou"},
    {"province_code": "15", "name_ar": "تيزي راشد", "name_en": "Tizi Rached"},
    {"province_code": "15", "name_ar": "واقنون", "name_en": "Wagnoun"},
    {"province_code": "16", "name_ar": "الجزائر", "name_en": "Algiers"},
    {"province_code": "16", "name_ar": "الدار البيضاء", "name_en": "Dar El Beida"},
    {"province_code": "16", "name_ar": "المرسى", "name_en": "Rouiba"},
    {"province_code": "17", "name_ar": "جيجل", "name_en": "Jijel"},
    {"province_code": "17", "name_ar": "تاجة", "name_en": "Taja"},
    {"province_code": "17", "name_ar": "قرة قول", "name_en": "Karakoule"},
    {"province_code": "18", "name_ar": "سطيف", "name_en": "Setif"},
    {"province_code": "18", "name_ar": "جميلة", "name_en": "Djemila"},
    {"province_code": "18", "name_ar": "بني ورتيلان", "name_en": "Beni Ourtilane"},
    {"province_code": "19", "name_ar": "سعيدة", "name_en": "Saida"},
    {"province_code": "19", "name_ar": "تيليلسي", "name_en": "Tilelsi"},
    {"province_code": "19", "name_ar": "قصر الشلالة", "name_en": "Kasr Chellala"},
    {"province_code": "20", "name_ar": "سكيكدة", "name_en": "Skikda"},
    {"province_code": "20", "name_ar": "الرمل", "name_en": "Collo"},
    {"province_code": "20", "name_ar": "عين بن بيضاء", "name_en": "Ain Ben Beida"},
    {"province_code": "21", "name_ar": "سيدي بلعباس", "name_en": "Sidi Bel Abbes"},
    {"province_code": "21", "name_ar": "بن باديس", "name_en": "Ben Badis"},
    {"province_code": "21", "name_ar": "سفيزف", "name_en": "Sfizef"},
    {"province_code": "22", "name_ar": "قسنطينة", "name_en": "Constantine"},
    {"province_code": "22", "name_ar": "عين سمارة", "name_en": "Ain Smara"},
    {"province_code": "22", "name_ar": "الخروب", "name_en": "El Khroub"},
    {"province_code": "23", "name_ar": "المدية", "name_en": "Medea"},
    {"province_code": "23", "name_ar": "الطاهرية", "name_en": "Tahriah"},
    {"province_code": "23", "name_ar": "سوقريس", "name_en": "Sougris"},
    {"province_code": "24", "name_ar": "مستغانم", "name_en": "Mostaganem"},
    {"province_code": "24", "name_ar": "عين تادلس", "name_en": "Ain Tadlis"},
    {"province_code": "24", "name_ar": "حاسي الرمل", "name_en": "Hassi El Rmel"},
    {"province_code": "25", "name_ar": "معسكر", "name_en": "Mascara"},
    {"province_code": "25", "name_ar": "أولاد ميمون", "name_en": "Ouled Mimoun"},
    {"province_code": "25", "name_ar": "تاريوة", "name_en": "Tarioua"},
    {"province_code": "26", "name_ar": "ورقلة", "name_en": "Ouargla"},
    {"province_code": "26", "name_ar": "حاسي بن عبد الله", "name_en": "Hassi Ben Abdallah"},
    {"province_code": "26", "name_ar": "البرمة", "name_en": "El Barma"},
    {"province_code": "27", "name_ar": "وهران", "name_en": "Oran"},
    {"province_code": "27", "name_ar": "السنيا", "name_en": "Arzew"},
    {"province_code": "27", "name_ar": "بير الجير", "name_en": "Bir El Djir"},
    {"province_code": "28", "name_ar": "البيض", "name_en": "El Bayadh"},
    {"province_code": "28", "name_ar": "الجبصة", "name_en": "El Jobsa"},
    {"province_code": "28", "name_ar": "فيرارة", "name_en": "Firara"},
    {"province_code": "29", "name_ar": "إليزي", "name_en": "Illizi"},
    {"province_code": "29", "name_ar": "الهقار", "name_en": "Hoggar"},
    {"province_code": "30", "name_ar": "برج بوعريريج", "name_en": "Bordj Bou Arreridj"},
    {"province_code": "30", "name_ar": "ذراع القايد", "name_en": "Daraia El Gaid"},
    {"province_code": "31", "name_ar": "بومرداس", "name_en": "Boumerdes"},
    {"province_code": "31", "name_ar": "الزرايا", "name_en": "Zraia"},
    {"province_code": "32", "name_ar": "الطارف", "name_en": "El Tarf"},
    {"province_code": "32", "name_ar": "بوطاهر", "name_en": "Boutaher"},
    {"province_code": "33", "name_ar": "تندوف", "name_en": "Tindouf"},
    {"province_code": "33", "name_ar": "أم الأغويل", "name_en": "Oum El Aghwil"},
    {"province_code": "34", "name_ar": "تسمسيلت", "name_en": "Tissemsilt"},
    {"province_code": "34", "name_ar": "الرحيبة", "name_en": "Larhriba"},
    {"province_code": "35", "name_ar": "الوادي", "name_en": "El Oued"},
    {"province_code": "36", "name_ar": "خنشلة", "name_en": "Khenchela"},
    {"province_code": "36", "name_ar": "بريكة", "name_en": "Briqa"},
    {"province_code": "37", "name_ar": "سوق أهراس", "name_en": "Souk Ahras"},
    {"province_code": "38", "name_ar": "تيبازة", "name_en": "Tipaza"},
    {"province_code": "39", "name_ar": "ميلة", "name_en": "Mila"},
    {"province_code": "40", "name_ar": "عين الدفلة", "name_en": "Ain Defla"},
    {"province_code": "41", "name_ar": "ناحية", "name_en": "Naama"},
    {"province_code": "42", "name_ar": "عين تيموشنت", "name_en": "Ain Temouchent"},
    {"province_code": "43", "name_ar": "غرداية", "name_en": "Ghardaia"},
    {"province_code": "44", "name_ar": "غليزان", "name_en": "Guelma"},
    {"province_code": "45", "name_ar": "البرج", "name_en": "Relizane"},
    {"province_code": "46", "name_ar": "موزاية", "name_en": "Mouzaia"},
    {"province_code": "47", "name_ar": "أولاد جلال", "name_en": "Ouled Djellal"},
    {"province_code": "48", "name_ar": "برج الباجي", "name_en": "Bordj El Kiffan"},
    {"province_code": "49", "name_ar": "الدراسة", "name_en": "El Achir"},
    {"province_code": "50", "name_ar": "أولاد أباي", "name_en": "Ouled Abbaya"},
    {"province_code": "51", "name_ar": "سيدي أيوب", "name_en": "Sidi Ayyoub"},
    {"province_code": "52", "name_ar": "عين الزرقاء", "name_en": "Ain Zerga"},
    {"province_code": "53", "name_ar": "واد سونة", "name_en": "Wadi Souf"},
    {"province_code": "54", "name_ar": "زامورة", "name_en": "Zamoura"},
    {"province_code": "55", "name_ar": "سبع سكان", "name_en": "Sabaa Sebian"},
    {"province_code": "56", "name_ar": "مقرة", "name_en": "Makra"},
    {"province_code": "57", "name_ar": "سيدي أمحمد", "name_en": "Sidi Mohamed"},
    {"province_code": "58", "name_ar": "بريدجة", "name_en": "Beridja"}
]

output_path = '/home/houdaifayahia/www/Laravel-Vue-Inertia-general-purpose/database/seeders/data/cities.json'
with open(output_path, 'w', encoding='utf-8') as f:
    json.dump(cities_data, f, ensure_ascii=False, indent=2)

print(f"✓ Created cities.json with {len(cities_data)} cities")
